apiVersion: apps/v1
kind: Deployment
metadata:
  name: netiframework
spec:
  replicas: 2
  selector:
    matchLabels:
      app: netiframework
  template:
    metadata:
      labels:
        app: netiframework
    spec:
      containers:
      - image: netiframework:latest
        name: netiframework
        env:
          - name: PASSWORD
            value: ""
        resources:
          limits:
            memory: 512Mi
            cpu: "1"

---

apiVersion: v1
kind: Service
metadata:
  name: netiframework
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:

  type: ClusterIP  
  ports:
  - name: "netiframework"
    port: 4200
  selector:
    app: netiframework
