apiVersion: v1
kind: Pod
metadata:
  name: netiframework-pod
spec:
  containers:
    - image: netiframework
      name: netiframework
      imagePullPolicy: Never
      resources: {}
      ports:
        - containerPort: 4200
      env:
        - name: PASSWORD
          value: ""